---
/joy:
  interpreter:
    ros__parameters:
      axis_linear.x: 1  # Left thumb stick vertical
      scale_linear.x: 0.2
      scale_linear_turbo: 1.5

      axis_angular.yaw: 3  # Left thumb stick horizontal
      scale_angular.yaw: 1.2

      enable_button: 4  # LB
      enable_turbo_button: 5  # RB
